// IPC channel name constants — prevents typos between preload/main

module.exports = {
	GET_API_KEY: 'get-api-key',
	EXECUTE_TOOL: 'execute-tool',
	CAPTURE_SCREEN: 'capture-screen',
	TOGGLE_VOICE: 'toggle-voice',
	TRACK_VOCABULARY: 'track-vocabulary',
	GET_VOCABULARY: 'get-vocabulary',
	GET_HOT_VOCABULARY: 'get-hot-vocabulary',
	GET_VOCABULARY_STATS: 'get-vocabulary-stats',
	GET_VOCABULARY_CORRECTIONS: 'get-vocabulary-corrections',
	GET_VOCABULARY_CORE: 'get-vocabulary-core',
	ADD_CORRECTION: 'add-correction',
	SEARCH_SPINNER: 'search-spinner',
	SEARCH_RESULT: 'search-result',
	SEARCH_HIDE: 'search-hide',
	MESSAGING_APP_FOCUSED: 'messaging-app-focused',
	MESSAGING_APP_LEFT: 'messaging-app-left',
	GET_SKILL_DECLARATIONS: 'get-skill-declarations',
	GET_SKILL_PROMPTS: 'get-skill-prompts',
	GET_SKILL_CATALOG: 'get-skill-catalog',
	SET_IGNORE_MOUSE: 'set-ignore-mouse',
	RELOAD_SESSION: 'reload-session',
	LOG_TO_FILE: 'log-to-file',
	KILL_SKILL: 'kill-skill',
	SAVE_CONVERSATION_TURN: 'save-conversation-turn',
	SAVE_TOOL_EXECUTION: 'save-tool-execution',
	SEMANTIC_SEARCH: 'semantic-search',
	NEW_CONVEX_SESSION: 'new-convex-session',
	END_CONVEX_SESSION: 'end-convex-session',
	LOAD_KANBAN_TASKS: 'load-kanban-tasks',
	SAVE_KANBAN_TASKS: 'save-kanban-tasks',
	UPDATE_KANBAN_TASK: 'update-kanban-task',
	RUN_SKILL: 'run-skill',
	RUN_TASK: 'run-task',
	RESIZE_KANBAN: 'resize-kanban',
};
