const EVENT_TYPES = {
	THINKING: 'THINKING',
	TOOL_START: 'TOOL_START',
	TOOL_END: 'TOOL_END',
	ACTION_VERIFY_OK: 'ACTION_VERIFY_OK',
	ACTION_VERIFY_FAIL: 'ACTION_VERIFY_FAIL',
	TASK_MILESTONE: 'TASK_MILESTONE',
	TASK_DONE: 'TASK_DONE',
	INTERRUPT: 'INTERRUPT',
	DB_HEALTH: 'DB_HEALTH',
	PROACTIVE_SUGGESTION: 'PROACTIVE_SUGGESTION',
	TWO_FA_FIELD_DETECTED: 'TWO_FA_FIELD_DETECTED',
	TWO_FA_FILL_START: 'TWO_FA_FILL_START',
	TWO_FA_FILL_SUCCESS: 'TWO_FA_FILL_SUCCESS',
	TWO_FA_FILL_FAILED: 'TWO_FA_FILL_FAILED',
	TWO_FA_LOW_CONFIDENCE: 'TWO_FA_LOW_CONFIDENCE',
	TWO_FA_NO_CODE: 'TWO_FA_NO_CODE',
};

module.exports = { EVENT_TYPES };
